### ISSUE TITLE
Initial planning - will need to move from this issue, putting here until we find a better place for it

### ISSUE THREAD

**Issue by samhstn** [InclusiveClassrooms/skills-wheel#1]
# Routes
Key
Superuser: S
Teacher: T

`/register`                     T
`/login`                        T, S
`/forgotten-password`           T, S
`/update-password`              T, S
`/admin/dashboard`           S
`/student-groups`            T, S
`/students/:groupid`            T, S
`/student/:studentid/form`      T
`/student/:studentid/summery`   T, S

# Schema
### admin_table
admin_id
name
email
password

### teacher_table
teacher_id
name
email
password

### group_table
group_id
teacher_id
name

### student_table
student_id
group_id
name
age
sex

### survey_table
survey_id
student_id
timestamp

### category_table
category_id
survey_id
name
color?

### question_table
question_id
category_id
question
answers

# User stories
As an admin I would like to...
  log in
  view list of teachers
  approve domains
  view spreadsheet data for every teacher
  access teacher view
  add ability to view google sheets

As a teacher I would like to...
  sign up & log in
  request a domain?
  view a list of groups
  view a list of students
  create/delete/edit groups
  create/delete/edit students
  view a student with seeing it's further history
  survey a student
    see a list of...
      categories
      questions
    see previous answers if they exist
    submit new answers

**Comment by jackcarlisle** [comment]
Closing, no longer needed
