### ISSUE TITLE
/forgotten-password :: POST

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#10]
[Back to API discussion](https://github.com/InclusiveClassrooms/skills-wheel/issues/6)

```elixir
incoming_data = %{email}
send_email(incoming_data)
```

Redirect to same page with a "check your emails..." message

**Comment by shouston3** [comment]
@nelsonic In terms of integrating the [sendemail module](https://github.com/dwyl/sendemail), we were thinking of starting a simple node microservice and hitting that from this endpoint.

Would this be a good way to go about solving this problem?
