### ISSUE TITLE
Skills Wheel: Research into D3

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#10]

**Comment by Danwhy** [comment]
Example of creating arcs with D3: http://jsfiddle.net/g0r9n090/

**Comment by Danwhy** [comment]
Creating arcs all the way round with border: http://jsfiddle.net/g0r9n090/616/

**Comment by Danwhy** [comment]
Making text follow a curved path http://www.visualcinnamon.com/2015/09/placing-text-on-arcs.html

**Comment by Danwhy** [comment]
updated wheel http://jsfiddle.net/g0r9n090/618/

**Comment by Danwhy** [comment]
Skills wheel is functional as of 8fd4274eb22a0beba059903478312742699a3ea4
