### ISSUE TITLE
CSS Cleanup

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#117]
There are a couple of things that need a tidy up after recent functionality has been added. These include:

- [x] Remove "Survey subheading" from survey
- [x] Update "submit" button styling on survey to match other buttons in the application
- [x] Format the "Admin Dashboard" button to fit within the navbar
- [x] fix the styling of the navbar on the survey view

**Comment by samhstn** [comment]
Fixed by #118
