### ISSUE TITLE
Proposed demo date

### ISSUE THREAD

**Issue by iteles** [InclusiveClassrooms/skills-wheel#131]
@ICHelen We'd like to propose 14h00 on Monday 27th as our final demo date. Does this work for you?

**Comment by ICHelen** [comment]
Hi Ines,

I'm busy on that Monday and Tuesday all day but could do Wednesday morning if you have some time then?

Many thanks,

Helen 

Helen Saddler
Director, Inclusive Classrooms

**Comment by iteles** [comment]
Booked for 30th March :+1:
