### ISSUE TITLE
Final demo flow

### ISSUE THREAD

**Issue by iteles** [InclusiveClassrooms/skills-wheel#160]
Before we start: set up a teaching assistant in the app

+ New Group
+ Create 2 new students
  + Talk about last initial being in student name
+ Do a second survey
  + Show previous answer
+ Talk through history
+ Download skills wheel
+ Edit group
  + Show changes reflected throughout
+ Show admin dashboard

## To dos
+ Add date to top skills wheel so it's clear which one it is 
+ In PDF download, make answers to info un-bold and increase whitespace between header and skills wheel
+ Change title of page to 'Skillswheel'
+ Add 'Groups' link to navigation
+ Fix 'Delete group' - gives internal server error
+ Add 'Back to groups' button at the bottom of edit group page
+ Admin data:
  + Make data headers white background with pink header
  + In spreadsheet, show the correct numbers (i.e. 1 instead of 0)
  + In spreadsheet, add new columns  :arrow_right: @iteles

**Comment by iteles** [comment]
@shouston3 Could you please convert the 'to-dos' into issues so we can close this issue? :blush:

**Comment by samhstn** [comment]
@iteles 👍 
Working from issue #161
