### ISSUE TITLE
/students :: GET/POST/PUT/DELETE

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#17]
[Back to API discussion](https://github.com/InclusiveClassrooms/skills-wheel/issues/6)

* [GET](https://github.com/InclusiveClassrooms/skills-wheel/issues/17#issuecomment-281311633)
* [POST](https://github.com/InclusiveClassrooms/skills-wheel/issues/17#issuecomment-281311893)
* [PUT](https://github.com/InclusiveClassrooms/skills-wheel/issues/17#issuecomment-281311908)
* [DELETE](https://github.com/InclusiveClassrooms/skills-wheel/issues/17#issuecomment-281311908)

**Comment by samhstn** [comment]
GET

We want to GET all of the students for a given group. A query to the database might look something like:

Query
```elixir
query = from s in Student,
          select: s.student_name, s.student_id, s.student_sex
Repo.all(query)
```

Response
```elixir
%{
  student_name: 'John Doe',
  student_id: 1111,
  student_sex: 'male'
}
```

**Comment by samhstn** [comment]
POST

When we want to create a new student we will send a post request to the `/students` endpoint. The payload will contain the following:

Payload
```elixir
%{
  student_name: 'John Doe',
  student_id: 1234
}
```

Query
```elixir
def create(conn, %{"student" => student}) do
  changeset = Student.changeset(%Student{}, student)
  case Repo.insert(changeset) do
  {:ok, student_data} ->
    render conn "students.html" student: student_data
  {:error, changeset} ->
   conn
   |> put_flash(:info, "Failed to create group"
   |> redirect(to: user_path(conn, :index))
  end
end
```

**Comment by samhstn** [comment]
PUT

We will be making a PUT request when we want to edit the details of a student (`student_name`). We will also need to validate that the field cannot be empty for the updated group name.

Payload
```elixir
%{
  student_name: 'John Doe',
  group_id: 1234,
  student_id: 1111
}
```

Query
```elixir
def edit(conn, %{"student_id" => student_id) do
  student = Repo.get(Student, student_id)
  changeset = Student.changeset(student)

  render conn, "student.html" changeset:changeset student: student
end
```

**Comment by samhstn** [comment]
DELETE

We will be making a DELETE request when we want to remove a student from the database. 

Payload
```elixir
%{
  student_id: 1111,
  group_id: 1234
}
```

Query
```elixir
def delete(conn, %{"student_id" => student_id}) do
  Repo.get!(Student, student_id)
    |> Repo.delete!

  conn
  |> put_flash(:info, "Student Deleted")
  |> redirect(to: student_path(conn, :index))
end
```
