### ISSUE TITLE
Data Collection: Sending data to Redis Database

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#18]

**Comment by iteles** [comment]
Linked to #13?

**Comment by Jbarget** [comment]
@iteles #13 was for writing the javascript to manipulate the form data to produce a nice JS object ready to store in the database

**Comment by Danwhy** [comment]
finished with 9efffbeaf99e31a73d1884ba5d838e4c4eba5b96
