### ISSUE TITLE
Integration with current website

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#19]
- ask current developer about Inclusive Classrooms' hosting
- see how to integrate skills wheel with website, if possible

**Comment by Jbarget** [comment]
@Danwhy sent email to current developer, waiting for a response

**Comment by Danwhy** [comment]
@ICHelen I've emailed Joe about the current hosting situation, but had no response.
Did you have the login details for the site? That might be enough for us to see what we can do with it.

**Comment by ICHelen** [comment]
Hi @Danwhy. Apologies that Joe hasn't responded- I've prompted him twice but he's very flaky! I have the login details below:

http://www.inclusiveclassrooms.co.uk/wp-login/php

username- admin
password- London2009

Hope it gives you the information you need. Let me know if you need more from Joe and I'll prompt him again.

Helen

**Comment by iteles** [comment]
Done! The skills wheel can now be found at `/skillswheel`.
