### ISSUE TITLE
Browser Compatibility?

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#2]
Would be good to know what browsers the teaching assistants use.
eg. Internet Explorer, Safari, Google Chrome, Firefox? And which version?

**Comment by Danwhy** [comment]
Microsoft have a remote client for testing sites on Internet Explorer and Edge on Mac: https://dev.windows.com/en-us/microsoft-edge/tools/remote/
Only IE 10 and above though.

**Comment by iteles** [comment]
Visual checks carried out in IE10+ and OS X Chrome, Safari and Firefox.

More will become apparent from user testing.
