### ISSUE TITLE
Add codecov.yml

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#22]
We should add a `codecov.yml` file so that we can display the coverage for the application more graphically within our PRs.

**Comment by samhstn** [comment]
Closed by #23

**Comment by iteles** [comment]
@shouston3 @jackcarlisle Codecov doesn't seem to have support for Elm just yet: https://github.com/dwyl/learn-elm/issues/5#issuecomment-274059753

**Comment by samhstn** [comment]
We're currently not planning to use elm in this project, but if we do we'll look at an alternative coverage tool
