### ISSUE TITLE
Questions for Helen

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#25]
what inputs would she like in terms of:

"Small form to fill in TA's details + child's details"

**Comment by Jbarget** [comment]
Are there SVG's available for the 4 faces to be used for rating?

**Comment by ICHelen** [comment]
Would be great to have the following inputs when TAs log on to input data on pupils:
TA Name, School, Child, Year, Group name (see below),

Might be useful to ask all TAs involved to give their intervention group a name, so that we can run analytics that will compare progress of students at group level, as well as school level. This way we can see if certain TAs are performing better than others, rather than just schools. Hope this makes sense!

**Comment by Jbarget** [comment]
@ICHelen thanks for this! sorry about referring to you in the 3rd person. I thought Ines might pick them up and ask you herself. :) 

We'll adjust the form accordingly, thanks.

RE: question about the faces, would you be able to send us the individual files for those faces (if there are a few different file types for each face could you send them all through)?

thanks thanks

**Comment by ICHelen** [comment]
Not at all- I'm amazed I've actually found what I need to look at already! What are the faces?! (apologies for my ignorance). If you mean parts of the wheel- all I have is what I sent across in the pdf. I can ask if they have anything more detailed if that's what you're looking for?

**Comment by Jbarget** [comment]
Ha nice one!

I meant these faces:

![screen shot 2016-02-22 at 12 45 20](https://cloud.githubusercontent.com/assets/11725595/13218534/28f3109c-d962-11e5-9a79-50c22271bc59.png)

It would be great to have the individual files for them, if not we'd just have to spend a bit of time making them

**Comment by ICHelen** [comment]
Hopefully this is what you're looking for...

[reskillswheelquestionsforhelen25.zip](https://github.com/InclusiveClassrooms/skills-wheel/files/140664/reskillswheelquestionsforhelen25.zip)

**Comment by Jbarget** [comment]
perfecto! thats exactly what we were after

**Comment by ICHelen** [comment]
Great- as it turns out the concept of 'faces' isn't too difficult to understand!!

**Comment by iteles** [comment]
Linked to #4

**Comment by Jbarget** [comment]
Hi Helen!

We were just thinking, for the details inputed for "Small form to fill in TA's details + child's details"

would it be helpful to have a full date or term or month/year to fill in? If so which would you want?

**Comment by ICHelen** [comment]
Hi @jbarget I think month and year would be best- otherwise it could get a bit confusing with term dates etc if we went for termly input phases. Thanks!
