### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by samhstn** [InclusiveClassrooms/skills-wheel#31]
Instead of using a `.env` file. Phoenix gives us a `config/prod.secret.exs` file for storing these which will take care of everything for us

**Comment by jackcarlisle** [comment]
@shouston3 perfect! Can you give an example of how to write variables in files like this?

**Comment by samhstn** [comment]
Sorry for the wierd example, but [this wiki](https://github.com/SantaMonicaElixir/werewolf/wiki/Deploying-to-Heroku#add-phoenix-production-configuration) explains how to set it up for their app, we could have similar instructions in our readme

**Comment by samhstn** [comment]
We're getting on fine with sourcing them for now
