### ISSUE TITLE
Groups and TAs

### ISSUE THREAD

**Issue by samhstn** [InclusiveClassrooms/skills-wheel#35]
Hi @ICHelen,

We were a little unsure of how the groups and teaching assistants were related, if possible could you describe how they are related addressing the following questions:

How many groups will a TA take charge of?
Are groups run by only one TA?

**Comment by ICHelen** [comment]
Hi Sam,

Each TA usually runs a group of between 5-10 students. Normally the TAs run groups independently, but some schools like to have 2 TAs running one group- there will never be more than 2 TAs running one group of children. 

Some schools also have individual TAs running multiple groups, so there could be a scenario in which one TA runs three separate groups of 5-10 children. So, in effect, they could be inputting data for 30 children, in theory.

Hope that makes sense!

Helen

**Comment by samhstn** [comment]
Perfect @ICHelen, that's given is a really good idea of the relationship.

Thanks for the fast response.
