### ISSUE TITLE
fix indentation in wheel.js

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#38]

**Comment by iteles** [comment]
@JBarget Is this is a visual fix? Code indentation?

If visual, please provide a screenshot 👍🏻

**Comment by Jbarget** [comment]
No, visual representation to the client, more just about neat code

**Comment by Danwhy** [comment]
fixed with 8fd4274eb22a0beba059903478312742699a3ea4
