### ISSUE TITLE
Improve coverage script

### ISSUE THREAD

**Issue by samhstn** [InclusiveClassrooms/skills-wheel#40]
At the moment [excoveralls](https://github.com/parroty/excoveralls) has been quite a pain:
* the [`coveralls.json`](https://github.com/InclusiveClassrooms/skills-wheel/blob/master/coveralls.json) file doesn't work
* it doesn't create a `cover` directory for us to work with
* the vanilla cover directory is difficult to move around in and work out where we are covering

Going to look into setting up the right flags to make a manageable `cover` directory that we can work with locally and to look at tweaking this so working with it's output will be easier

**Comment by jackcarlisle** [comment]
@shouston3 have there been any updates with this?

**Comment by samhstn** [comment]
Fixed by #42
