### ISSUE TITLE
Brand guidelines

### ISSUE THREAD

**Issue by iteles** [InclusiveClassrooms/skills-wheel#5]
Website: http://www.inclusiveclassrooms.co.uk/

Provided by the lovely Helen:

<img width="762" alt="inclusive-classroom-colour-palette" src="https://cloud.githubusercontent.com/assets/4185328/13214768/5ddfe5be-d949-11e5-9497-48c2cd4ebb4f.png">

**Comment by Jbarget** [comment]
Open Sans:

https://www.google.com/fonts#UsePlace:use/Collection:Open+Sans

**Comment by Jbarget** [comment]
Varela Round:

https://www.google.com/fonts#UsePlace:use/Collection:Varela+Round

**Comment by iteles** [comment]
Used for the designs, looking good! Linked to #54 #4
