### ISSUE TITLE
Create low-fidelity paper sketch/wireframes for each view

### ISSUE THREAD

**Issue by samhstn** [InclusiveClassrooms/skills-wheel#5]
### Teaching Assistant 
- [x] Register 
- [x] Log in  
- [x] Forgotten password 
- [x] Create new password
- [x] Group Dashboard
- [x]  Students Dashboard
- [x] Student Profile
- [x] New Survey Form
- [x] Student Skills History

### Admin
- [x] Teaching Assistant Dashboard
- [x] Aggregated data dashboard

**NOTE:** Admin will have access to all of the views that the teaching assistant has (but not necessarily all of the functionality)

**Comment by jackcarlisle** [comment]
Teaching Assistant flow:
![ta-flow](https://cloud.githubusercontent.com/assets/12450298/23131139/de2c1336-f780-11e6-96df-3c9b183bf1ed.jpg)

**Comment by jackcarlisle** [comment]
Admin views:

![admin-flow](https://cloud.githubusercontent.com/assets/12450298/23131710/f8d23ccc-f782-11e6-9204-54ae0277e54d.jpg)

**Comment by nelsonic** [comment]
Which reminds me: we need new whiteboards (_or at least a better way to clean our existing ones..._) 😉

**Comment by jackcarlisle** [comment]
Closing as wireframes have been developed much further by @harrygfox
