### ISSUE TITLE
School Dropdown Menu upon Register

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#50]
As a teaching assistant,
I want to be able to select my school from a list of schools when registering,
So that I can be grouped appropriately

**Comment by jackcarlisle** [comment]
## Changes

As per our stand up this morning, we are going to remove the dropdown from the registration page so that it protects the system from anyone registering with dummy emails. Instead we are going to infer the school from the email address provided, and if it doesn't match an email in the database, we will send back a descriptive error message like:

>"Your school is not in the system, please contact [contact email] to request access"

**Comment by harrygfox** [comment]
@jackcarlisle 
I like the cleverness of this system. When there's hidden consequences to actions we need to ensure the user is adequately informed ahead of time: To avoid the user having to enter their email address, create a password etc, and click submit, and **_only then_** realise that their school isn't in the system:

1. I think we should have a message on this view letting the user know that _"SkillsWheel is only available to certain schools"_ and _"if you'd like to use the SkillsWheel at your school please get in touch"_ (link to emailing a person).

2. When they do enter their details and click submit and are presented with an error - show a more human-friendly error e.g. _"Sorry, it looks like SkillsWheel has not come to your school yet. If you'd like to gain access please get in touch here"_ or something like that

**Comment by jackcarlisle** [comment]
@harrygfox sounds good! We can make those changes 👍

**Comment by jackcarlisle** [comment]
Before user interaction:
<img width="1305" alt="screen shot 2017-03-02 at 10 39 12" src="https://cloud.githubusercontent.com/assets/12450298/23503649/815f39d8-ff34-11e6-9bf1-3a9d2acc9bf9.png">
After user interaction:
<img width="1305" alt="screen shot 2017-03-02 at 10 38 58" src="https://cloud.githubusercontent.com/assets/12450298/23503677/9469bb02-ff34-11e6-9f13-183824986fad.png">

@harrygfox will update with proper styling when appropriate

**Comment by jackcarlisle** [comment]
Closing, resolved with #57
