### ISSUE TITLE
Apply different colours for each section on skills wheel

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#54]

**Comment by Jbarget** [comment]
@iteles we've implemented this but the purple doesnt work well with the grey that Helen sent over.
Would you or Helen like us to try and find a better match of purple?

![screen shot 2016-02-26 at 17 05 30](https://cloud.githubusercontent.com/assets/11725595/13359347/a9e51406-dcab-11e5-9387-f2b723cb0c5b.png)

**Comment by iteles** [comment]
@Jbarget Could you drop in a screenshot with a lighter shade of purple and then also one of all the squares coloured in orange (the wheel's main colour), so Helen can choose which one works aesthetically for her? Given that the change is quick for us and makes a big difference aesthetically?

**Comment by Jbarget** [comment]
Heres the example of a different shade of purple that would work:

![screen shot 2016-02-28 at 12 54 25](https://cloud.githubusercontent.com/assets/11725595/13379317/7861686a-de1a-11e5-975e-0eb43f0d5982.png)

**Comment by Jbarget** [comment]
here's the wheel with all one colour:

![screen shot 2016-02-28 at 12 55 53](https://cloud.githubusercontent.com/assets/11725595/13379327/aae019b2-de1a-11e5-8802-658aeb0c8d0a.png)

**Comment by Jbarget** [comment]
in my opinion the different shade of purple looks the best, but let me know what you want to do @iteles

**Comment by iteles** [comment]
This is a question for @ICHelen :)

**Comment by Jbarget** [comment]
For future reference if needed this is the alternative purple hex colour #672a99

**Comment by Jbarget** [comment]
fixed with 00f394e
