### ISSUE TITLE
School/Teaching Assistant Access Request

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#58]
Hi @ICHelen,

We have been creating the user registration form for teaching assistants. If a teaching assistant is trying to access the system from a school that isn't signed up, what email address should they get in touch with to request access?

Thanks!

**Comment by ICHelen** [comment]
Hi Jack,

They can contact me directly- helen@inclusiveclassrooms.co.uk.

Best wishes,

Helen 

Helen Saddler
Director, Inclusive Classrooms
