### ISSUE TITLE
CI Build 100%

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#63]
At the moment we are intermittently experiencing a drop in coverage on some of our `model` test files locally. We are still investigating as to why this is the case but haven't found an answer yet.

**Comment by jackcarlisle** [comment]
Possible solution might be to add a script that drops our database before tests run: 

`psql -c "drop database skillswheel_test`

**Comment by jackcarlisle** [comment]
@shouston3 found an example of explicitly testing the schema which should cover all of the intermittent lines

**Comment by samhstn** [comment]
After trying quite a few hacky attempts to solving this, we were unable to consistently get the coverage to reach 100%.

To see the problem yourself:
Follow the quick start guides.
Then run `mix coveralls.html`.
Every so often you will see that coverage won't be 100% and when examining your
`cover/excoveralls.html` file, you will see that the `schema` line isn't covered

![screen shot 2017-03-06 at 16 30 21](https://cloud.githubusercontent.com/assets/15983736/23619046/49963c3c-028a-11e7-9b91-35f29535bd46.png)

We will continue getting around this problem by restarting the travis build on coverage failing until it passes

This is really not a solution at all, with further models we will be more and more likely to have failing travis tests. For a larger project, this will be a real blockage

**Comment by samhstn** [comment]
You can see how ecto test this line here: https://github.com/elixir-ecto/ecto/blob/master/test/ecto/schema_test.exs

**Comment by samhstn** [comment]
No longer looking to deal with this problem here. Note has been made in `dwyl/learn-phoenix-framework`
