### ISSUE TITLE
User Dashboard CSS

### ISSUE THREAD

**Issue by jackcarlisle** [InclusiveClassrooms/skills-wheel#74]
After receiving the wireframes from @harrygfox we are now in a position to begin working on the styles for each view. 

- [ ]  add styling for User Dashboard

<img width="1625" alt="screen shot 2017-03-06 at 17 14 52" src="https://cloud.githubusercontent.com/assets/12450298/23620869/73c356c4-0290-11e7-85af-e818be216740.png">

**Comment by jackcarlisle** [comment]
Style update. Current state of groups page: 
<img width="1017" alt="screen shot 2017-03-07 at 11 02 23" src="https://cloud.githubusercontent.com/assets/12450298/23653781/91ca3d32-0325-11e7-8fdd-950657ac5013.png">

**Comment by jackcarlisle** [comment]
Update: 
<img width="1191" alt="screen shot 2017-03-07 at 17 28 16" src="https://cloud.githubusercontent.com/assets/12450298/23669278/7cfd314e-035b-11e7-834a-68b3502de9cf.png">

**Comment by samhstn** [comment]
Looks so good

**Comment by samhstn** [comment]
Fixed #77
