### ISSUE TITLE
Add whitespace (and fix margin on tablet)

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#78]

**Comment by Jbarget** [comment]
@Danwhy the margin is back again on the right in tablet view, can you see an issue being caused by me moving [these lines](https://github.com/InclusiveClassrooms/skills-wheel/blob/master/public/index.html#L801-L806) within the div that ends above them?

**Comment by Jbarget** [comment]
thats what i did last time to fix it but the changes aren't present in master, ive had a look back through the commit history as well and cant find where is was changed after I fixed it :confused:

**Comment by Jbarget** [comment]
linked to #57

**Comment by Danwhy** [comment]
Hopefully won't be a problem. Let's give it a try
