### ISSUE TITLE
Main Page: HTML Styling

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#8]
Style form (with help from bootstrap?)

**Comment by iteles** [comment]
Could we get a screenshot in here of how it looks when you're done? :)

**Comment by Jbarget** [comment]
sure thing

**Comment by Jbarget** [comment]
initial commit dfc58ce

**Comment by Jbarget** [comment]
fixed with b0d1b9afd5e3ca8a9b77e87cad910619526dd8a8
