### ISSUE TITLE
Bug: Details on side of PDF too large and being cut off by the wheel

### ISSUE THREAD

**Issue by Jbarget** [InclusiveClassrooms/skills-wheel#82]
![screen shot 2016-03-01 at 19 47 35](https://cloud.githubusercontent.com/assets/11725595/13439690/91daa0b8-dfe6-11e5-9e66-5c859a83a2c4.png)

**Comment by Danwhy** [comment]
How's this? <img width="1180" alt="screen shot 2016-03-01 at 21 44 42" src="https://cloud.githubusercontent.com/assets/8939909/13443011/e68a67e6-dff6-11e5-8963-26d8fb918d80.png">

**Comment by iteles** [comment]
👍🏻
