### ISSUE TITLE
Demo flow 

### ISSUE THREAD

**Issue by iteles** [InclusiveClassrooms/skills-wheel#92]
+ Go to register and try with non-accepted school
+ Login and a dwyl.io email address
  + Note that it logs you straight in
+ 2 new groups
+ Create new student
+ Click into student
+ Back to groups
+ Log out
+ Forgotten password flow
+ Mention standard login
+ Incognito window - straight to admin, add stmarys.co.uk
+ Now register as a st. mary's school email user

**Actions:**
+ Remove dummy skills wheel from student
+ Add logo

**Comment by iteles** [comment]
Feedback from demo call:
+ Add last name to student circles (consideration around what to do with long last names) 
+ Edit student and edit group flows
+ Add previous skills wheel to student page
  + Download as PDF with strong copy 'please save this now as it's your last chance'
+ Admin page redirect 
+ Call to be had next Tuesday on admin data flow

**Comment by jackcarlisle** [comment]
@iteles can this be closed or shall we use this for the final demo flow as well?

**Comment by iteles** [comment]
@jackcarlisle This was only still open until the feedback had been translated into issues. If that's done, feel free to close it!
